### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by JGaed** [scychon/openmm_constV#2]
Hello!

I want to simulate an ionic liquid (with a drude pol. force field) between two planar electrodes, so I stumbled across your plugin for OpenMM. It seems great for what I want to do, since I already wrote the whole force field for OpenMM - and compiled your plugin into it. Would it be possible to provide an example system, similar to your Drude plugin? It would really help me a lot!

Bests!

**Comment by scychon** [comment]
Thanks for the interest in using our constV plugin ! We're in the final review process for publication of the paper for this work (likely to show up in a month at the latest), and plan to put the example after the official acceptance from the journal. I'll post an update ASAP if there's any changes.

**Comment by JGaed** [comment]
Thank you very much for your fast response - I will see forward to your publication!

**Comment by scychon** [comment]
Just to let you know that our paper got online at PNAS today ! https://www.pnas.org/content/118/19/e2020615118
Also I added an example for simple NaCl in water using non-polarizable force field.
I'll add more examples for using Drude polarizable force field and tabulated functions soon.
